### ISSUE TITLE
Test BT-8 Issue

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/bluetooth#1]
During the review of the Bluetooth Module the reviewer had a comment about FMT_SMF_EXT.1 Test BT-8. The Test EA in question is as follows:

_The evaluator shall verify that all supported Bluetooth services and/or profiles are listed in the TSS as manageable and, if the TOE allows disabling by application rather than by service and/or profile name, that a list of services and/or profile for each application is also listed._ 

The evaluator comment is that this is phrased as a TSS EA despite being under the Test section. We would like to rewrite the first part of the EA to be something like this so that it’s more specifically related to testing:

_For each supported Bluetooth service and/or profile listed in the TSS, the evaluator shall verify that the service or profile is manageable._

However, I’m not sure about how to address the second part of it. Is this EA saying that if Bluetooth functionality enabled/disabled on a per-app basis that the actual TOE must identify the services and/or profiles associated with each app? Or is this saying that it’s acceptable for the TOE to only control this on a per-app basis as long as the TSS is making it clear what services and/or profiles are associated with given apps?

**Comment by dmhale1** [comment]
SME reviewed and agreed that the rewrite to "For each supported Bluetooth service and/or profile listed in the TSS, the evaluator shall verify that the service or profile is manageable." is acceptable.

**Comment by jfisherbah** [comment]
Change already made in previous revision. Note that the test also includes the following: "If this is configurable by application rather than by service and/or profile name, the evaluator shall verify that a list of services and/or profiles for each application is also listed" since that was covered by the original test but not the proposed change.
