### ISSUE TITLE
suppression of invisible f-components

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/bluetooth#11]
The f-component ftp_blt_ext.3 (with no iteration) is flagged with status="invisible" in the input XML but it is showing up in the mandatory SFRs section. It has appropriately been suppressed from all other places (e.g. consistency rationale table) and is appropriately showing up in the ECD, but the actual component should not be present in the main body of the Module.

**Comment by robertmclemons** [comment]
I don't the invisible component in the mandatory SFR section.

**Comment by jfisherbah** [comment]
This is from the latest version for me:

***@***.***D72C62.EAA04C70]

Regards,
Justin

From: Bob Clemons ***@***.***>
Sent: Thursday, April 8, 2021 10:11 AM
To: commoncriteria/bluetooth ***@***.***>
Cc: Fisher, Justin M. [US-US] ***@***.***>; Author ***@***.***>
Subject: EXTERNAL: Re: [commoncriteria/bluetooth] suppression of invisible f-components (#11)


CAUTION: This email originated from outside of Leidos. Be cautious when clicking or opening content.

I don't the invisible component in the mandatory SFR section.

**Comment by jfisherbah** [comment]
Just checked the latest versions of each and it’s present in bluetooth.html and bluetooth-release-linkable.html, but not in bluetooth-release.html. So that probably explains it. I generally work off the ones with EAs built into the page rather than having the Module and SD open in separate tabs.

Regards,
Justin

From: Fisher, Justin M. [US-US]
Sent: Thursday, April 8, 2021 10:36 AM
To: 'commoncriteria/bluetooth' ***@***.***>; commoncriteria/bluetooth ***@***.***>
Cc: Author ***@***.***>
Subject: RE: EXTERNAL: Re: [commoncriteria/bluetooth] suppression of invisible f-components (#11)

This is from the latest version for me:

***@***.***D72C65.3AFC6EE0]

Regards,
Justin

From: Bob Clemons ***@***.***>
Sent: Thursday, April 8, 2021 10:11 AM
To: commoncriteria/bluetooth ***@***.***>
Cc: Fisher, Justin M. [US-US] ***@***.***>; Author ***@***.***>
Subject: EXTERNAL: Re: [commoncriteria/bluetooth] suppression of invisible f-components (#11)


CAUTION: This email originated from outside of Leidos. Be cautious when clicking or opening content.

I don't the invisible component in the mandatory SFR section.
