### ISSUE TITLE
FMT_SMF_EXT.1/Bluetooth EA discrepancy

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/bluetooth#12]
The guidance evaluation activities for the GPOS PP version of FMT_SMF_EXT.1/Bluetooth includes the following: "The evaluator shall verify that the operational guidance describes the Out of Band pairing methods if selected." The MDF PP version of this SFR does not define the same activity. It is unclear whether the discrepancy is intentional, whether this statement should be removed from the GPOS section for consistency, or whether it should be added to the MDF section for discrepancy.

**Comment by dmhale1** [comment]
Per SME, the statement should be removed from the GPOS section for consistency.

**Comment by jfisherbah** [comment]
Statement in question removed and replaced with a copy of the MDF EA in latest revision.
