### ISSUE TITLE
testing for FTP_BLT_EXT.1

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/bluetooth#13]
The current test EAs for FTP_BLT_EXT.1 includes a negative test for BR/EDR that shows an encryption attempt is rejected when an insufficiently large key is used. It is unclear whether this is necessary because it appears to be a duplicate of FTP_BLT_EXT.3/BR Test 3. If two distinct tests are intended, it is recommended that FTP_BLT_EXT.1 testing be clarified so that it is clearly distinct from what FTP_BLT_EXT.3/BR requires. Otherwise, the test should be removed.

Additionally, "LE" is selectable in the SFR but there is no conditional testing for LE. If testing separate from FTP_BLT_EXT.3/LE is expected for this SFR, one or more appropriate conditional tests need to be devised.

**Comment by dmhale1** [comment]
Per SME, the test should be removed.

**Comment by jfisherbah** [comment]
Testing removed and replaced with a note that this SFR is addressed through testing of FTP_BLT_EXT.3/BR and, if claimed, FTP_BLT_EXT.3/LE.
