### ISSUE TITLE
App note discrepancy in FMT_SMF_EXT.1/Bluetooth

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/bluetooth#14]
The MDF PP version of FMT_SMF_EXT.1/Bluetooth has a bullet in its application note that is absent from the GPOS version of the same SFR ("Examples of levels of security are..."). It is unclear whether the discrepancy is intentional or if the same note should be added to the GPOS version or removed from the MDF version for consistency.

**Comment by dmhale1** [comment]
Per SME, the same note should be added to the GPOS version.

**Comment by jfisherbah** [comment]
Added to GPOS version in latest build
