### ISSUE TITLE
Function BT-4 discrepancy in FMT_SMF_EXT.1/Bluetooth

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/bluetooth#15]
The management function BT-4 in FMT_SMF_EXT.1/Bluetooth is different in the MDF vs GPOS versions of the SFR. It is unclear whether this should be kept as-is or if one of them should be changed to match the other for consistency. It is believed that the MDF version should be used for GPOS as the GPOS version is missing a selection but it's unclear if that is the case or if different modifications need to be made (e.g. because GPOS should have different selections from MDF).

**Comment by dmhale1** [comment]
Per SME, it should be changed to match the other PP for consistency.

**Comment by jfisherbah** [comment]
BT-4 updated to have the selectable version for both Base-PPs
