### ISSUE TITLE
/Bluetooth -> /BLUETOOTH or /BT

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/bluetooth#16]
Looking at the WLAN and VPN PP-Modules, it looks odd to have mixed case compared to the WLAN and VPN modules. I would recommend changing it to be all caps.

If there is a concern for the acronyms vs name, it would be easy to just use /BT (which would also be shorter for everyone involved typing) in its place.

**Comment by dmhale1** [comment]
Agree with changing to /BT

**Comment by jfisherbah** [comment]
All iteration names changed from "/Bluetooth" to "/BT" in latest build
