### ISSUE TITLE
FAU_GEN.1/BLUETOOTH title

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/bluetooth#17]
The WLAN PP-Module has FAU_GEN.1 titled:

FAU_GEN.1/WLAN Audit Data Generation (Wireless LAN)

The VPN Client PP-Module similarly has "(VPN Client)" at the end of the title.

It seems like the BT one should also have "(Bluetooth)" added at the end of it for consistency.

**Comment by dmhale1** [comment]
Agreed

**Comment by jfisherbah** [comment]
Added " (Bluetooth)" to FAU_GEN.1 title in latest build
