### ISSUE TITLE
FMT_SMF_EXT.1/Bluetooth for MDF columns are inconsistent

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/bluetooth#18]
In the MDF v3.2, the FMT_SMF_EXT.1 table columns are labeled:

- Impl. (Implemented)
- User Only
- Admin
- Admin Only

But in the BT they are using the older labels of:

- FMT_SMF_EXT.1
- FMT_MOF_EXT.1.1
- Admin
- FMT_MOF_EXT.1.2

This is likely due to an MDF update after the BT doc has largely been completed, but should be edited for consistency with the MDF FMT tables.

**Comment by dmhale1** [comment]
Agreed

**Comment by jfisherbah** [comment]
changed table headers to match comment in latest build
