### ISSUE TITLE
Suppression of blank tables in consistency rationale

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/bluetooth#5]
Following on issue #2, the second and third section of the consistency rationales (consistency of SPD and consistency of objectives) auto-populate all of their text except for the second sentence that we put in there (“This PP-Module does not add or remove any…”). Everything aside from those sentences in those sections should be suppressed when no elements of the given type exist but there’s currently no way to do it.

**Comment by dmhale1** [comment]
Bob removed the unnecessary text.
